### ISSUE TITLE
Module source error

### ISSUE THREAD

**Issue by vshanthappa** [terraform-aviatrix-modules/terraform-aviatrix-aws-sandbox-starter#1]
source       = "terraform-aviatrix-modules/sandbox-starter/aviatrix"

Error:

initializing modules...
╷
│ Error: Module not found
│ 
│ Module "sst" (from main.tf:1) cannot be found in the module registry at registry.terraform.io.
╵

╷
│ Error: Module not found
│ 
│ Module "sst" (from main.tf:1) cannot be found in the module registry at registry.terraform.io.
╵

**Comment by vshanthappa** [comment]
need to update doc notes to have source as below

  source  = "terraform-aviatrix-modules/aws-sandbox-starter/aviatrix"

**Comment by jb-smoker** [comment]
Updates to readme packaged in the 1.0.1 release
